imports:
  - { resource: parameters.yml }
  - { resource: services.yml }
  - { resource: curse.yml }

framework:
  #esi:             ~
  translator: { fallbacks: ["%locale%"] }
  secret: "%secret%"
  router:
    resource: "%kernel.root_dir%/config/routing.yml"
    strict_requirements: ~
  form: ~
  csrf_protection: ~
  validation: { enable_annotations: true }
  templating:
    engines: ['twig']
  default_locale: "%locale%"
  trusted_proxies: ~
  session:
    handler_id: session.handler.native_file
    save_path: "%kernel.root_dir%/../var/sessions/"
  fragments: ~
  http_method_override: true

web_profiler:
  toolbar: true
